import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Roboto_Serif } from "next/font/google";

const RobotoSerif = Roboto_Serif({
  subsets: ["latin"],
  weight: 'variable',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RobotoSerif} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
